# Generated by Django 4.1 on 2024-07-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tru_gio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ten', models.CharField(max_length=250)),
                ('cong_suat', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Thong_so',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('Most_restrictive_WTG_Status', models.FloatField(default=0)),
                ('Average_Active_Power', models.FloatField(default=0)),
                ('WG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Giamsat.tru_gio')),
            ],
        ),
    ]
