# Generated by Django 4.1 on 2024-07-10 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tru_gio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.CharField(max_length=250)),
                ('ten', models.CharField(max_length=250)),
                ('cong_suat', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=255, null=True)),
                ('Most_restrictive_WTG_Status_10M', models.FloatField(default=0)),
                ('WTG_nacelle_position_corrected_Average_10M', models.FloatField(default=0)),
                ('Active_power_Std_Dev_10M', models.FloatField(default=0)),
                ('Ambient_Temperature_Std_Dev_10M', models.FloatField(default=0)),
                ('Average_Active_Power_10M', models.FloatField(default=0)),
                ('Average_Ambient_Temperature_10M', models.FloatField(default=0)),
                ('Average_Generator_Speed_10M', models.FloatField(default=0)),
                ('Average_Grid_Voltage_10M', models.FloatField(default=0)),
                ('Average_Nacelle_Position_10M', models.FloatField(default=0)),
                ('Average_Pitch_Angle_10M', models.FloatField(default=0)),
                ('Average_Reactive_Power_10M', models.FloatField(default=0)),
                ('Average_Rotor_Speed_10M', models.FloatField(default=0)),
                ('Average_Stator_Active_Power_10M', models.FloatField(default=0)),
                ('Average_Wind_Speed_10M', models.FloatField(default=0)),
                ('Bearing_DE_Temperature_10M', models.FloatField(default=0)),
                ('Bearing_DE_Temperature_dv_10M', models.FloatField(default=0)),
                ('Bearing_DE_Temperature_max_10M', models.FloatField(default=0)),
                ('Bearing_DE_Temperature_min_10M', models.FloatField(default=0)),
                ('Bearing_NDE_Temperature_10M', models.FloatField(default=0)),
                ('Bearing_NDE_Temperature_dv_10M', models.FloatField(default=0)),
                ('Bearing_NDE_Temperature_max_10M', models.FloatField(default=0)),
                ('Bearing_NDE_Temperature_min_10M', models.FloatField(default=0)),
                ('Wind_farm_active_power_dv_10M', models.FloatField(default=0)),
                ('Wind_farm_active_power_max_10M', models.FloatField(default=0)),
                ('Wind_farm_active_power_min_10M', models.FloatField(default=0)),
                ('tru_gio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='Giamsat.tru_gio')),
            ],
        ),
    ]
