# Generated by Django 4.1 on 2024-07-05 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tru_gio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.CharField(max_length=250)),
                ('ten', models.CharField(max_length=250)),
                ('cong_suat', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Thong_so',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.CharField(max_length=250)),
                ('Most_restrictive_WTG_Status', models.FloatField(default=0)),
                ('Average_Active_Power', models.FloatField(default=0)),
                ('Average_Ambient_Temperature', models.FloatField(default=0)),
                ('Average_Generator_Speed', models.FloatField(default=0)),
                ('Average_Nacelle_Position', models.FloatField(default=0)),
                ('Average_Rotor_Speed', models.FloatField(default=0)),
                ('Average_Stator_Active_Power', models.FloatField(default=0)),
                ('Average_Wind_Speed', models.FloatField(default=0)),
                ('Bearing_D_E_Temperature', models.FloatField(default=0)),
                ('Bearing_D_E_Temperature_max', models.FloatField(default=0)),
                ('Bearing_N_D_E_Temperature', models.FloatField(default=0)),
                ('Bearing_N_D_E_Temperature_max', models.FloatField(default=0)),
                ('Gearbox_bearing_temperature', models.FloatField(default=0)),
                ('Gearbox_bearing_temperature_max', models.FloatField(default=0)),
                ('Gearbox_oil_temperature', models.FloatField(default=0)),
                ('Gearbox_oil_temperaturemax', models.FloatField(default=0)),
                ('Generator_windings_temperature_1', models.FloatField(default=0)),
                ('Generator_windings_temperature_1_max', models.FloatField(default=0)),
                ('Generator_windings_temperature_2', models.FloatField(default=0)),
                ('Generator_windings_temperature_2_max', models.FloatField(default=0)),
                ('Generator_windings_temperature_3', models.FloatField(default=0)),
                ('Generator_windings_temperature_3_max', models.FloatField(default=0)),
                ('Generators_sliprings_temperature', models.FloatField(default=0)),
                ('Generators_sliprings_temperature_max', models.FloatField(default=0)),
                ('Hidraulic_group_pressure', models.FloatField(default=0)),
                ('Mean_theoretical_power_last_10_minutes', models.FloatField(default=0)),
                ('Nacelle_Misalignment_and_Average_Wind_Direction', models.FloatField(default=0)),
                ('Trafo_1_winding_temperature', models.FloatField(default=0)),
                ('Trafo_1_winding_temperature_max', models.FloatField(default=0)),
                ('Trafo_2_winding_temperature', models.FloatField(default=0)),
                ('Trafo_2_winding_temperature_max', models.FloatField(default=0)),
                ('Trafo_3_winding_temperature', models.FloatField(default=0)),
                ('Trafo_3_winding_temperature_max', models.FloatField(default=0)),
                ('WG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Giamsat.tru_gio')),
            ],
        ),
    ]
